### ISSUE TITLE
Return a wrapped class from a Function

### ISSUE THREAD

**Issue by jojolatina** [ayles/v8bind#1]
I have created a class like this:
```cpp
class Foo
{
  int a;
  int b;
  public:
  Foo(int a, int b): a(a), b(b) {}
};

v8b::Module module(isolate);

v8b::Class<Foo> fooClass(isolate);
fooClass.Constructor<std::tuple<int ,int>>()
.Var("a", &Foo::a)
.Var("b", &Foo::b);

module.Class("Foo", fooClass);
```

This works perfectly but now I have a function that returns a Foo:
```cpp
Foo f() {
  Foo foo(1, 2);
  ...
  return foo;
}

module.Function("f", &f);
```

But when I call `f` from Javascript, I get the message "Error: Can't find wrapped object [class Foo]".

Isn't it possible to return a non-primitive value from a function?

**Comment by ayles** [comment]
> Isn't it possible to return a non-primitive value from a function?

Yep, it is possible, but by design it is better to return object by reference/pointer/smart pointer, cause it is not so clear how objects returned by value and their lifetime should be managed in JS context.

First of all, if you want to auto wrap your objects, you shold set `Class::AutoWrap(true)`. Otherwise you should always call `Class::WrapObject` before returning it.

Secondly, now this will not work with stack-allocated objects at all (I forgot to add some assertions).

So just create object with `new` on heap, then wrap it with`Class::WrapObject()` and pass `true` as `take_ownership`, so object will be deleted with `delete` when there will be no references to it in js context.
Then you can just return pointer to `Foo`.

If you will just return pointer to `Foo` with `Class::AutoWrap(true)` but without `WrapObject(take_ownership = true)`, things will work fine but library will not delete your object at all so you will be responsible for freeing memory.

Using `shared_ptr` is better cause object will not be deleted while *there is `shared_ptr`'s to it* **and** *wrapper in js is not collected by gc*

**Comment by ayles** [comment]
Oh, yes, and if you want to use some factory function as constructor in JS, there is overload of `Constructor` function on `Class` that takes just any number of factory functions returning `T*`, if I remember it right.

**Comment by jojolatina** [comment]
Thanks, setting `AutoWrap(true)` solved the problem but now I have a new one, my class Foo has a static property of type `Foo`, like this:

```cpp
class Foo
{
  int a;
  int b;
  public:
  Foo(int a, int b): a(a), b(b) {}
  static Foo STATIC_FOO;
};
```

And I would like to add it to JS like `Foo.STATIC_FOO` so I did:
```cpp
v8b::Class<Foo> fooClass(isolate);
fooClass.Constructor<std::tuple<int ,int>>()
.Var("a", &Foo::a)
.Var("b", &Foo::b)
.StaticConst("STATIC_FOO", Foo::STATIC_FOO);
```

But unfortunately it doesn't work, it crashes with a `V8BindException`. How can I add a static property that is of a non-primitive type? (it works like a charm if `STATIC_FOO` is `int` for example)

**Comment by jojolatina** [comment]
Ok it seems that we can’t wrap anything before a context is running or something but It doesn’t matter I don’t need it anymore
